### ISSUE TITLE
Better Documentation on Workflow Example

### ISSUE THREAD

**Issue by Zageron** [fateyan/action-discord-notifier#1]
```bash
 Set up job
  LTS
Current runner version: '2.263.0'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200604.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200604.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'binotaliu/action-discord-notifier@v1.2.0'
```

```bash

Run binotaliu/action-discord-notifier@v1.2.0
    webhook: ***
Run binotaliu/action-discord-notifier@v1.2.0
  with:
    webhook: ***
evalmachine.<anonymous>:23142
const commits = githubPayload.commits.map(i => ` - [\`[${shortSha(i.id)}]\`](${i.url}) ${escapeMd(i.message)} - by ${i.author.name}`)
                                      ^

TypeError: Cannot read property 'map' of undefined
    at Object.562 (evalmachine.<anonymous>:23142:39)
    at __webpack_require__ (evalmachine.<anonymous>:22:30)
    at startup (evalmachine.<anonymous>:37:19)
    at evalmachine.<anonymous>:41:18
    at evalmachine.<anonymous>:44:10
    at Object.<anonymous> (/home/runner/work/_actions/binotaliu/action-discord-notifier/v1.2.0/dist/index.js:5:28)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

**Comment by ghost** [comment]
Which trigger event do you use? It currently only support for `push` and `pull_request` ?

**Comment by Zageron** [comment]
Pull request open and reopen, same crash.

**Comment by Zageron** [comment]
https://github.com/flashflashrevolution/rCubed/blob/main/.github/workflows/pull-request-notification.yml

**Comment by Zageron** [comment]
Sorry, I'm a dumb ass I didn't check out the repository.

**Comment by ghost** [comment]
I haven't got a time to look at this issue. But good to see you find the answer yourself.

This is still a problem that cause by **the leak of documentation.** Let me reopen this issue and write a better readme.

**Comment by Zageron** [comment]
Yeah, a complete functioning example would have resolved this. I didn't think I had to use the checkout action, but in hindsight the error message was clearly failing on the lack of a repository.

**Comment by Zageron** [comment]
Here's my functioning example.
```yaml
on:
  pull_request:
    types: [opened, reopened]

name: Pull Request Discord Notification
jobs:
  discordNotification:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - uses: Ilshidur/action-discord@759f6ea
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
```
