### ISSUE TITLE
Posting with webhook returns error 400

### ISSUE THREAD

**Issue by durkmurder** [fateyan/action-discord-notifier#2]
When trying to post using discord webhook, getting error 400
That's all logs: `##[error]Post to webhook failed, Error: Request failed with status code 400`

**Comment by fateyan** [comment]
Hi, it may be a little bit too late to reply to you, but if you still need help, please send me your yaml file.

BTW, don't know if this commit helps 679ea94

**Comment by sidedwards** [comment]
@fateyan I'm also getting this error. I've tried regenerating the webhook, but that didn't resolve the issue.

Here's my yaml file.
``` yaml
name: Discord Notification

on:
  push:
    branches: [ master ]

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Deploy
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
```
