### ISSUE TITLE
[Bug] - TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sidedwards** [fateyan/action-discord-notifier#6]
I'm getting the following error when trying to run an action when an issue is opened with a particular tag.

```
TypeError: Cannot read property 'map' of undefined
    at Object.562 (evalmachine.<anonymous>:23142:39)
    at __webpack_require__ (evalmachine.<anonymous>:22:30)
    at startup (evalmachine.<anonymous>:37:19)
    at evalmachine.<anonymous>:41:18
    at evalmachine.<anonymous>:44:10
    at Object.<anonymous> (/home/runner/work/_actions/fateyan/action-discord-notifier/v1.2.0/dist/index.js:5:28)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

It looks like it fails at this line:
```js
const commits = githubPayload.commits.map(i => ` - [\`[${shortSha(i.id)}]\`](${i.url}) ${escapeMd(i.message)} - by ${i.author.name}`)
```

Here is my workflow action for reference.
```yml
name: Discord Bug Report

on:
  issues:
    types: [opened]

jobs:
  notify:
    name: Discord Bug Report
    if: "contains(github.event.issue.labels.*.name, 'type:\ bug')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Bug Report
          webhook: <secret>
```
